
set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include(CTest)
include(FetchContent)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG   ${PROJECT_SOURCE_DIR}/bin/debug)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${PROJECT_SOURCE_DIR}/bin/release)

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG   ${PROJECT_SOURCE_DIR}/bin/debug/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${PROJECT_SOURCE_DIR}/bin/release/lib)

set(DEPS_DIR ${CMAKE_SOURCE_DIR}/deps)
set(APPS_DIR ${CMAKE_SOURCE_DIR}/src/apps)
set(LIBS_DIR ${CMAKE_SOURCE_DIR}/src/libs)
set(INCLUDES_DIR ${CMAKE_SOURCE_DIR}/includes)
set(DEMOS_DIR ${CMAKE_SOURCE_DIR}/demos)

set(BUILD_TARGET_NTG_LIB TRUE)
set(BUILD_TARGET_NTG_IR TRUE)
set(BUILD_TARGET_NTG_BLENDER TRUE)
set(BUILD_TARGET_NTG_CLI TRUE)
set(BUILD_TARGET_NTG_VIZ FALSE)
set(BUILD_DEMOS TRUE)
